server {
  listen 80;
  server_name localhost;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name localhost;

  ssl_certificate /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/nginx.key;

  client_max_body_size 0;

  root /var/www/html;
  index index.php index.html index.htm;

  # Deny all with deny without logs
  error_page 418 = @block_with_deny;
  location @block_with_deny {
    deny all;
    access_log off;
    log_not_found off;
  }

  # Deny access to /?shop/*
  if ($args ~* "^shop/") {
    return 418;
  }

  # Deny access to /xmlrpc.php
  location ^~ /xmlrpc.php {
    return 418;
  }

  # Deny access to /search.php
  location ^~ /search.php {
    return 418;
  }

  # Disable .htaccess and other hidden files except .well-known
  location ~ /\.(?!well-known).* {
    return 418;
  }

  # Disable logs favicon
  location = /favicon.ico {
    access_log off;
    log_not_found off;
  }

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass wordpress:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

  # Access the NGINX status page, also known as ngx_http_stub_status_module
  location /status {
    stub_status on;
    access_log  off;
    allow 127.0.0.1;
    deny all;
  }

}
